# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            No Joke Scala
tagline:          'A blog on robust Scala development'
description:      'A blog on robust Scala development. Written by <a href="https://github.com/WojciechP">Wojciech Ptak</a>.'
baseurl:          /

author:
  name:           'Wojciech Ptak'
  url:            https://github.com/WojciechP

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/WojciechP/nojokescala

gems:
  - jekyll-redirect-from
